######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 28 18:44:47 2020
######################################################################

TEMPLATE = app
#TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp

QMAKE_CXXFLAGS += -static -static-libgcc -static-libstdc++

