######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 28 18:44:47 2020
######################################################################
QT += widgets
TEMPLATE = app
#TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp

QMAKE_CXXFLAGS += -static -static-libgcc -static-libstdc++