######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 21 18:44:47 2023
######################################################################
QT += widgets
TEMPLATE = app
#TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp

QMAKE_CXXFLAGS += -static -static-libgcc -static-libstdc++
