######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 28 18:44:47 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += snake.h
SOURCES += main.cpp snake.cpp

QMAKE_CXXFLAGS += -static -static-libgcc -static-libstdc++

